# opencv version
OPENCV_VERSION := 3


INCLUDE_DIRS := /usr/local/include /usr/include/mysql
LIBRARY_DIRS := /usr/local/lib/opencv330 /usr/lib/x86_64-linux-gnu

# build dir
BUILD_DIR := build

LIBRARIES := opencv_core opencv_highgui opencv_imgproc mysqlclient z m dl hiredis
